apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-config
data:
  DB_NAME: postgres
  DB_USERNAME: postgres
  DB_HOST: coworking-postgresql
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
data:
  DB_PASSWORD: b1ZmWU84ZnNJdGh3d1BXam54QXJPSjBv